[[plugin]]
id = "thatonecalculator/um5606_fan_state"
name = "ASUS UM5606 Fan State"
version = "1.0.6"
min_noctalia = "5.0.0"
author = "ThatOneCalculator"
license = "MIT"
tags = ["asus", "hardware", "system"]
icon = "car-fan"
description = "Set the fan state on the ZenBook S 16 UM5606."
